### ISSUE TITLE
Crashes on Android Kitkat, Class not found on path DexPathList. I have multidex enabled.

### ISSUE THREAD

**Issue by denniskeithgaso** [ozodrukh/CircularReveal#103]
I get this stacktrace which s
FATAL EXCEPTION: main
                                                              Process: com.gaso.psa, PID: 23014
                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gaso.psa/com.gaso.psa.SplashscreenActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class io.codetail.widget.RevealFrameLayout
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                  at android.os.Looper.loop(Looper.java:193)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:515)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
                                                                  at dalvik.system.NativeStart.main(Native Method)
                                                               Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class io.codetail.widget.RevealFrameLayout
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:707)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                  at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:305)
                                                                  at android.app.Activity.setContentView(Activity.java:1944)
                                                                  at com.gaso.psa.SplashscreenActivity.onCreate(SplashscreenActivity.java:44)
                                                                  at android.app.Activity.performCreate(Activity.java:5264)
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                  at android.os.Looper.loop(Looper.java:193) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5292) 
                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                  at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640) 
                                                                  at dalvik.system.NativeStart.main(Native Method) 
                                                               Caused by: java.lang.ClassNotFoundException: Didn't find class "io.codetail.widget.RevealFrameLayout" on path: DexPathList[[zip file "/mnt/asec/com.gaso.psa-1/pkg.apk"],nativeLibraryDirectories=[/mnt/asec/com.gaso.psa-1/lib, /vendor/lib, /system/lib]]
                                                                  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                  at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:559)
                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:469) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                  at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:305) 
                                                                  at android.app.Activity.setContentView(Activity.java:1944) 
                                                                  at com.gaso.psa.SplashscreenActivity.onCreate(SplashscreenActivity.java:44) 
                                                                  at android.app.Activity.performCreate(Activity.java:5264) 
                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302) 
                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
                                                                  at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
                                                                  at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                  at android.os.Looper.loop(Looper.java:193) 
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5292) 
                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                  at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640) 
                                                                  at dalvik.system.NativeStart.main(Native Method)

**Comment by ozodrukh** [comment]
`./gradlew clean` must help

**Comment by denniskeithgaso** [comment]
Thanks. I discovered that it doesn't work on kitkat because I used the
debug apk from android lollipop. Kitkat doesn't support instant run
feature. Instant run contains a dex file for debugging not supported by
kitkat and lower. Must be either release build or compiled directly as
debug apk for Android kitkat emulator or device.
