### ISSUE TITLE
When start animator throw UnsupportedOperationException

### ISSUE THREAD

**Issue by qinqinany** [ozodrukh/CircularReveal#107]
It works on SamSung GT-P7510 Devices when start animator  throw some exception
```
java.lang.UnsupportedOperationException
                                                                   at android.view.GLES20Canvas.clipPath(GLES20Canvas.java:413)
                                                                   at io.codetail.animation.ViewRevealManager$RevealValues.applyTransformation(ViewRevealManager.java:182)
                                                                   at io.codetail.animation.ViewRevealManager.transform(ViewRevealManager.java:88)
                                                                   at io.codetail.widget.RevealFrameLayout.drawChild(RevealFrameLayout.java:31)
                                                                   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2497)
                                                                   at android.view.View.getDisplayList(View.java:10617)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2605)
                                                                   at android.view.View.getDisplayList(View.java:10582)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2605)
                                                                   at android.view.View.getDisplayList(View.java:10582)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2605)
                                                                   at android.view.View.getDisplayList(View.java:10582)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2605)
                                                                   at android.view.View.getDisplayList(View.java:10582)
                                                                   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2605)
                                                                   at android.view.View.getDisplayList(View.java:10582)
                                                                   at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:890)
                                                                   at android.view.ViewRootImpl.draw(ViewRootImpl.java:2113)
                                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1837)
                                                                   at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2649)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                   at android.os.Looper.loop(Looper.java:137)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:4512)
                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:511)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:978)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
                                                                   at dalvik.system.NativeStart.main(Native Method)
```

**Comment by imknown** [comment]
Duplicated https://github.com/ozodrukh/CircularReveal/issues/100
