### ISSUE TITLE
get Exception

### ISSUE THREAD

**Issue by Geekince** [ozodrukh/CircularReveal#27]
java.lang.UnsupportedOperationException    at android.view.GLES20Canvas.clipPath(GLES20Canvas.java:412)
At 4.0.3 version device

**Comment by vkislicins** [comment]
Getting the same issue on the latest version 2.0.1

Here's the stack trace:

```
08-05 19:07:42.689: E/AndroidRuntime(8672): java.lang.UnsupportedOperationException
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.GLES20Canvas.clipPath(GLES20Canvas.java:417)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at io.codetail.animation.ViewRevealManager$RevealValues.applyTransformation(ViewRevealManager.java:182)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at io.codetail.animation.ViewRevealManager.transform(ViewRevealManager.java:88)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at io.codetail.widget.RevealLinearLayout.drawChild(RevealLinearLayout.java:31)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2573)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.View.draw(View.java:11018)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.View.getDisplayList(View.java:10454)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2934)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1140)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2573)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.View.getDisplayList(View.java:10452)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2934)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1377)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2573)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.View.getDisplayList(View.java:10452)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2934)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2573)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.View.getDisplayList(View.java:10452)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2934)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2573)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.View.getDisplayList(View.java:10452)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2934)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2573)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.View.getDisplayList(View.java:10452)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2934)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2573)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.View.getDisplayList(View.java:10452)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.ViewGroup.drawChild(ViewGroup.java:2934)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2573)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.View.draw(View.java:11018)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.widget.FrameLayout.draw(FrameLayout.java:450)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2144)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.View.getDisplayList(View.java:10454)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:856)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2089)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1787)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2642)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.os.Looper.loop(Looper.java:154)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at android.app.ActivityThread.main(ActivityThread.java:4624)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at java.lang.reflect.Method.invokeNative(Native Method)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at java.lang.reflect.Method.invoke(Method.java:511)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
08-05 19:07:42.689: E/AndroidRuntime(8672): 	at dalvik.system.NativeStart.main(Native Method)
```
