### ISSUE TITLE
java.lang.IllegalStateException: Already started!

### ISSUE THREAD

**Issue by vipulasri** [ozodrukh/CircularReveal#48]
I having this error on Android 5.0.2, Samsung

<code>
java.lang.IllegalStateException: Already started!
       at android.view.RenderNodeAnimator.start(RenderNodeAnimator.java:177)
       at io.codetail.animation.SupportAnimatorLollipop.start(SupportAnimatorLollipop.java:35)
       at com.bakar.view.animation.RevealLayoutAnim.hide(RevealLayoutAnim.java:69)
       at com.bakar.ui.publish.MessagePublishActivity.hideReveal(MessagePublishActivity.java:549)
       at com.bakar.ui.publish.MessagePublishActivity$4.onClick(MessagePublishActivity.java:424)
       at android.view.View.performClick(View.java:5217)
       at android.view.View$PerformClick.run(View.java:20983)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6141)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
</code>

**Comment by ozodrukh** [comment]
@vipulasri Thanks, I will look at this some later
